#\u041E\u0431\u043D\u043E\u0432\u043B\u0451\u043D\u043D\u044B\u0435 \u0441\u0432\u043E\u0439\u0441\u0442\u0432\u0430
#Wed Nov 12 08:10:16 MSK 2025
window.horizontalSize=900
story.number=12562 (12573)
story.key=credit-organisation-card-refactoring
window.verticalSize=900
migration.profiles.allWithoutSarAndRegionalCurator=AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,COORDINATOR_DNSZKO,ANALYST_STBN,ANALYST_DNSZKO,METHODOLOGIST_STBN,METHODOLOGIST_DNSZKO
migration.profiles.allWithoutSar=REGIONAL_CURATOR,AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,COORDINATOR_DNSZKO,ANALYST_STBN,ANALYST_DNSZKO,METHODOLOGIST_STBN,METHODOLOGIST_DNSZKO
migration.author=69KreslinVYU
abac.fileName=AbacProfiles.txt
migration.profiles.all=REGIONAL_CURATOR,EMPLOYEE_SAR,AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,COORDINATOR_DNSZKO,ANALYST_STBN,ANALYST_DNSZKO,METHODOLOGIST_STBN,METHODOLOGIST_DNSZKO
story.fromExcel=true
migration.tabName=\u0420\u0435\u0430\u043B\u0438\u0437\u043E\u0432\u0430\u0442\u044C \u0440\u0430\u0431\u043E\u0442\u0443 \u0441 \u0441\u0443\u0431\u043E\u0440\u0434\u0438\u043D\u0438\u0440\u043E\u0432\u0430\u043D\u044B\u043C\u0438 \u0438\u043D\u0441\u0442\u0440\u0443\u043C\u0435\u043D\u0442\u0430\u043C\u0438
excel.rowSelector=i
abac.attributeCodeFilePath=attributeCodeFilePath.txt
window.size.vertical=900
migration.profiles.baAndOther=BUSINESS_ADMINISTRATOR,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_DNSZKO,ANALYST_DNSZKO
project.pathExcel=/home/69kreslinvyu@region.cbr.ru/Desktops/Desktop1/\u0437\u0430\u0434\u0430\u0447\u0438
story.shouldWriteAbacFile=true
migration.profiles.allWithoutSarAndRegionalCuratorAndCoordinatorAnalystMethotologDNSZKO=AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,ANALYST_STBN,METHODOLOGIST_STBN
window.size.horizontal=900
story.name=\u0418\u0437\u043C\u0435\u043D\u0438\u0442\u044C \u0441\u0442\u0440\u0443\u043A\u0442\u0443\u0440\u0443 \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0438 \u041A\u041E
window.title=KOH (KO Helper)
