window.size.horizontal=900
window.size.vertical=900
window.title=KOH (KO Helper)

story.author=KreslinVYu
story.number=12562 (12573)
story.name=Изменить структуру карточки КО
story.key=credit-organisation-card-refactoring
story.shouldWriteAbacFile=true
story.fromExcel=true

abac.fileName=AbacProfiles.txt
abac.attributeCodeFilePath=attributeCodeFilePath.txt

excel.rowSelector=13

# Migration application configuration
migration.keyText=subord_instrument
migration.author=69KreslinVYU
migration.storyNumber=PDKO-267(PDKO-256)
migration.tabName=Реализовать работу с субординироваными инструментами

# Profile groups configuration
migration.profiles.all=REGIONAL_CURATOR,EMPLOYEE_SAR,AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,COORDINATOR_DNSZKO,ANALYST_STBN,ANALYST_DNSZKO,METHODOLOGIST_STBN,METHODOLOGIST_DNSZKO
migration.profiles.allWithoutSarAndRegionalCurator=AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,COORDINATOR_DNSZKO,ANALYST_STBN,ANALYST_DNSZKO,METHODOLOGIST_STBN,METHODOLOGIST_DNSZKO
migration.profiles.allWithoutSar=REGIONAL_CURATOR,AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,COORDINATOR_DNSZKO,ANALYST_STBN,ANALYST_DNSZKO,METHODOLOGIST_STBN,METHODOLOGIST_DNSZKO
migration.profiles.allWithoutSarAndRegionalCuratorAndCoordinatorAnalystMethotologDNSZKO=AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,ANALYST_STBN,METHODOLOGIST_STBN
migration.profiles.baAndOther=BUSINESS_ADMINISTRATOR,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_DNSZKO,ANALYST_DNSZKO