window.size.horizontal=900
window.size.vertical=900
window.title=KOH (KO Helper)

story.number=12562 (12573)
story.name=ÐÐ·Ð¼ÐµÐ½Ð¸ÑÑ ÑÑÑÑÐºÑÑÑÑ ÐºÐ°ÑÑÐ¾ÑÐºÐ¸ ÐÐ
story.key=credit-organisation-card-refactoring
story.shouldWriteAbacFile=true
story.fromExcel=true

abac.fileName=AbacProfiles.txt
abac.attributeCodeFilePath=attributeCodeFilePath.txt

excel.rowSelector=i

# Migration application configuration
migration.author=69KreslinVYU
migration.tabName=Ð ÐµÐ°Ð»Ð¸Ð·Ð¾Ð²Ð°ÑÑ ÑÐ°Ð±Ð¾ÑÑ Ñ ÑÑÐ±Ð¾ÑÐ´Ð¸Ð½Ð¸ÑÐ¾Ð²Ð°Ð½ÑÐ¼Ð¸ Ð¸Ð½ÑÑÑÑÐ¼ÐµÐ½ÑÐ°Ð¼Ð¸

# Profile groups configuration
migration.profiles.all=REGIONAL_CURATOR,EMPLOYEE_SAR,AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,COORDINATOR_DNSZKO,ANALYST_STBN,ANALYST_DNSZKO,METHODOLOGIST_STBN,METHODOLOGIST_DNSZKO
migration.profiles.allWithoutSarAndRegionalCurator=AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,COORDINATOR_DNSZKO,ANALYST_STBN,ANALYST_DNSZKO,METHODOLOGIST_STBN,METHODOLOGIST_DNSZKO
migration.profiles.allWithoutSar=REGIONAL_CURATOR,AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,COORDINATOR_DNSZKO,ANALYST_STBN,ANALYST_DNSZKO,METHODOLOGIST_STBN,METHODOLOGIST_DNSZKO
migration.profiles.allWithoutSarAndRegionalCuratorAndCoordinatorAnalystMethotologDNSZKO=AUDITOR,BUSINESS_ANALYST_GIBR,BUSINESS_ADMINISTRATOR,CURATOR_STBN,CURATOR_GIBR,CURATOR_DFS,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_STBN,ANALYST_STBN,METHODOLOGIST_STBN
migration.profiles.baAndOther=BUSINESS_ADMINISTRATOR,CURATOR_DNSZKO,MANAGER_CURATOR_OBN,COORDINATOR_DNSZKO,ANALYST_DNSZKO